---
- hosts: localhost
  tasks:
    - name: making directories
      file:
        state: directory
        path: "{{ansible_env.HOME}}/{{item.path}}"
      with_filetree: HOME/
      when: item.state == 'directory'

    - name: configuration file linking
      file:
        state: link
        src: "{{item.src}}"
        dest: "{{ansible_env.HOME}}/{{item.path}}"
        force: true
      with_filetree: HOME/
      when: item.state == 'file'

